CREATE TABLE "MI181_JSBASS"."member" 
   (	"ID" NUMBER(4,0) NOT NULL ENABLE, 
	"MEM_FNAME" VARCHAR2(15) NOT NULL ENABLE, 
	"MEM_LNAME" VARCHAR2(15) NOT NULL ENABLE, 
	"MEM_MI" VARCHAR2(2) NOT NULL ENABLE, 
	"MEM_ADDRESS" VARCHAR2(45) NOT NULL ENABLE, 
	"MEM_SEX" VARCHAR2(15) NOT NULL ENABLE, 
	 CONSTRAINT "MEMBER_PKEY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE TABLE "MI181_JSBASS"."memberpayment" 
   (	"ID" NUMBER(4,0) NOT NULL ENABLE, 
	"PAY_AMOUNT" NUMBER(4,0) NOT NULL ENABLE, 
	"PAY_DATE" DATE NOT NULL ENABLE, 
	"PAY_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"MEMBER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "MEMBERPAYMENT_PKEY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MEMBER_PAYMENT" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "MI181_JSBASS"."member" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



CREATE OR REPLACE VIEW MI181_JSBASS.MEMBERPAYMENTS2
(ID,MEM_FNAME,MEM_LNAME,MEM_SEX,PAY_AMOUNT,PAY_TYPE,PAY_DATE)
AS
SELECT "member".id,
    "member".mem_fname,
    "member".mem_lname,
    "member".mem_sex,
    "memberpayment".pay_amount,
    "memberpayment".pay_type,
    "memberpayment".pay_date
FROM MI181_JSBASS."member"
JOIN MI181_JSBASS."memberpayment" ON "member".id = "memberpayment".member_id


